### ISSUE TITLE
 BleApiTest_TransportLimits()

### ISSUE THREAD

**Issue by denizea** [jovasco/u2f-ref-code#1]
Hi Johan,

I have been playing with your testing tool. I am also sniffing exchanging packets in the air as well.

On BleApiTest_TransportLimits() the tool sends following data and our authenticator sends back as following:

Tool: 0x81 0x00 0x01 0x00 0x00 0x00 ...... 0x00
Auth: 0xBF 0x00 0x01 0x02

I am using Error Constant Values as mentioned on FIDO BLE Spec. However, testing tool says:

WARN_NE fail at BleApiTest_TransportLimits[192]:reply[0] != ERR_INVALID_LEN:
 BleApiTest_TransportLimits[193]:   Limit is smaller than 2048 bytes.

I feel that your authenticator supports data more than 2K however, this could not be the case for other vendors. 

What do you think?

Have a great day!

**Comment by jovasco** [comment]
Hi Deniz,

the test is meant to find the limits of the Authenticator and doubles the size each iteration. If your authenticator doesn't fail at 2k, it will happen at 4k, 8k, ... The test only requires the Authenticator to correctly return an error to succeed. The warning you see is that the error value in the returned error is not what it expects (ERR_INVALID_LEN).

Are you sure that the request you included in the report is the request that caused the error? The length doesn't seem right: the request you give above says it is 1 byte length while the error message says it tried with 2K.

The warning is because according to the latest BLE spec, the error value for ERR_INVALID_LEN is 0x03, while the response you included in your report says 0x02.

Best regards,
Johan

**Comment by denizea** [comment]
Thanks Johan. This is right. Spec is updated with new Error values.
