### ISSUE TITLE
Bad CLA test should accept  68 81 (Logical Channel not Supported)

### ISSUE THREAD

**Issue by chriswifx** [jovasco/u2f-ref-code#6]
WRITE: 83000701030000000000
   READ: 820003019000
   READ: 820003019000
   READ: 8300026881
   READ: 8300026881
CHECK_EQ fail at BleApiTest_BadCLA[107]:FIDO_RESP_CLA_NOT_SUPPORTED != bytes2short(reply, 0):

**Comment by jovasco** [comment]
First, this test has an equivalent in the USB HID tests. If we change this, we also need to change it in the HID tests. We really do not want two different transports causing a different error value return on raw message level. Our solution also needs to include already certified devices out there

That said,

I ran into the same problem and had the same reaction, however, I changed my mind. Since the specs dictate this value should be 0, interpreting the value of this byte is a bug. It just doesn't make sense interpreting an illegal value. If you don't interpret this byte, the 6E00 reply is entirely appropriate.

**Comment by chriswifx** [comment]
Johan,

I seem to remember we hit this in NFC. There we had to accept 68 81 as it's a legitimate response from a smartcard os and we have no ability to interpret the data before it hits the smartcard.

The only way not to get that response is to interpret the message at the ble layer which seems to defeat the point of u2f layer test? 

The important thing is that an error response is present so why not accept either response? 

Sent from my phone, please forgive the typos.

Regards - Chris

**Comment by chriswifx** [comment]
Or alternatively, change the cla in the test to one that is not interpreted by the smartcard os but given to the applet? 

Sent from my phone, please forgive the typos.

Regards - Chris

**Comment by jovasco** [comment]
I was not familiar with the NFC case and I understand that it can't be intercepted there because there isn't actually an intermediate layer.

This test tests with a value of 0x01. What will be the error value for the 253 other CLA values? 
What about the CLA values that have meaning and do not create an error? they are still illegal.
What about implementations that use logical channels internally?

**Comment by chriswifx** [comment]
They all get treated as per iso7816.

The counter argument is that it seems a bizarre architecture to have iso 7816 commands and response formats and not allow iso compliant error messages? 

Putting in the change to detect the cla at the transport layer is trivial, and I have no problem doing it, but it does seem a confused way of doing things to me personally. It seems additional functionality for no gain to me.

As I said isn't the important point that an error is raised, not which particular error is raised? 

Sent from my phone, please forgive the typos.

Regards - Chris

**Comment by jovasco** [comment]
But we aren't ISO 7816 compliant. We had to "clarify" the raw messages spec to even get NFC to work.

I am not against changing the test, I would however discuss it on the TWG mailing list before making a change. I really think this should be consistent across certification tests. For example, a device that uses BLE, NFC and USB interfaces should not have to generate different errors on the different transports to pass tests (falling back to require any error in all tests would solve this).

Falling back to requiring any error is an acceptable solution to me but then I would still expect an error for all non-zero CLA values and you would still need to change your firmware since there is no guarantee all CLA values would cause an error in your smartcard. Have you investigated all possible CLA values and their possible side-effects on your applet?

**Comment by jovasco** [comment]
The test has been changed to send a random non-zero CLA and accept ANY error value in return that isn't 0x9000
